local template = require(script.Parent.genewation.pwegenewated)
local Shared = game:GetService("ReplicatedStorage").Shared
local Replication = require(script.Parent.ballhandwer)
local Physics = require(Shared:WaitForChild("phwsics"))

--require(script.Parent.genewation).generate(template.CustomNoise)

local Camera = workspace.CurrentCamera

-- local ball = Physics.newBall(Vector3.new(0, 100, 0),10)
-- local ball2 = Physics.newBall(Vector3.new(20, 100, 0),10)
-- local ball3 = Physics.newBall(Vector3.new(20, 150, 0),10)

-- workspace.CurrentCamera.CameraSubject = ball.part
